---
# First play
- name: Install node and npm
  hosts: instances
  become: true
  tasks:
    # - name: Update apt repo and cache
    #   ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 force_apt_get=true
    - name: Install nodejs and npm
      dnf: 
        pkg:
          - nodejs
          - npm
    - name: Create linux User
      user:
        name: nithin
        comment: nithin Admin
        group: ec2-user
#Second play
- name: Deploy nodejs app
  hosts: instances
  become: True
  become_user: nithin
  tasks:
    - name: Unpack the nodejs file
      unarchive:
        src: /home/nithin/folderForAnsible/folderforansible-1.0.0.tgz
        dest: /home/nithin
    - name: Install dependencies
      npm:
        path: /home/nithin/package
    - name: Start the application
      command: 
        chdir: /home/nithin/package
        cmd: node index.js 
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - name: debug
      debug: msg={{app_status}}